version: "3.4"
services:

  api:
    container_name: api
    build: .
    command: "python /www/src/api.py"
    ports:
      - 80:80
    volumes:
      - ./:/www/
    environment:
      MYSQL_HOSTNAME: database
      MYSQL_USERNAME: icu_username
      MYSQL_PASSWORD: icu_password
      MYSQL_DATABASE: icu_database
    depends_on:
      - database

  simulator:
    container_name: simulator
    build: .
    command: "python /www/simulator.py"
    volumes:
      - ./:/www/
    environment:
      MYSQL_HOSTNAME: database
      MYSQL_USERNAME: icu_username
      MYSQL_PASSWORD: icu_password
      MYSQL_DATABASE: icu_database
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:5.7.25
    environment:
      MYSQL_USER: icu_username
      MYSQL_PASSWORD: icu_password
      MYSQL_ROOT_PASSWORD: icu_rootpass
      MYSQL_DATABASE: icu_database
    volumes:
      - ./data/db_structure:/docker-entrypoint-initdb.d
      - ./data/db_data:/var/lib/mysql

  # Interface for our own MySQL database
  phpmyadmin:
    container_name: database-manager
    image: phpmyadmin/phpmyadmin:4.8.5
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      MYSQL_USER: icu_username
      MYSQL_PASSWORD: icu_password
